### ISSUE TITLE
doesn't work with 3.14.4

### ISSUE THREAD

**Issue by folkertvanheusden** [TheJokr/tcpreq#1]
```
(venv) root@bruto:/home/folkert/t/myip/tcpreq# python3 -m tcpreq -B 192.168.1.1 -r 10 -T '*' -o results.json 192.168.1.2:80
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/folkert/t/myip/tcpreq/tcpreq/__main__.py", line 200, in <module>
    main()
    ~~~~^^
  File "/home/folkert/t/myip/tcpreq/tcpreq/__main__.py", line 173, in main
    t = test(ipv4_host, tgt, loop=loop)  # type: ignore
  File "/home/folkert/t/myip/tcpreq/tcpreq/tests/base.py", line 43, in __init__
    self.recv_queue: "asyncio.Queue[bytearray]" = asyncio.Queue(loop=loop)
                                                  ~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: Queue.__init__() got an unexpected keyword argument 'loop'
```
